# Generated by Django 4.1.7 on 2023-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_is_doctor_customuser_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='on_hold',
            field=models.BooleanField(default=True, verbose_name='appointment waiting for review'),
        ),
    ]
