# Generated by Django 4.1.7 on 2023-03-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_on_hold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='patient_proposed_date',
        ),
    ]
