# Generated by Django 4.1.7 on 2023-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_appointment_date_appointment_patient_proposed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
