# Generated by Django 4.1.7 on 2023-03-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_doctor_emergency_line_alter_doctor_landline_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialization',
        ),
    ]
