# Generated by Django 4.1.7 on 2023-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=70),
        ),
    ]
